### ISSUE TITLE
List not found

### ISSUE THREAD

**Issue by willbraden** [MikoMagni/Trello-Workflow-for-Alfred#11]
I can't seem to get this workflow to push to Trello. I have entered my personal token, and the boardid. However, I keep getting the "List not found." result. The only edits I've made to the file are those required in the /bin/bash.

Any thoughts?

Thanks!

**Comment by ablo** [comment]
Seems like the Board needs to be set to "Public". Any way around this @MikoMagni?

@willbraden

**Comment by willbraden** [comment]
Interesting. Yes I'm curious about any fixes for private. My information is more than likely not sensitive, but something still makes me not like setting to public.

Thanks for the find.

**Comment by jipiboily** [comment]
Interestingly, it worked (I think) for a couple cards, but not anymore...or maybe I'm too tired and mixing this up with the other plugin I tried? Anyways, getting the same issue.

**Comment by jipiboily** [comment]
The token is invalid, but when hardcoding it, it works...for some reason, it kept spitting an invalid token, which was not the one I've put. With that changed, directly in the PHP script (and I'm using my own API key), it works.
