### ISSUE TITLE
Not work for me

### ISSUE THREAD

**Issue by yuanxj1024** [MikoMagni/Trello-Workflow-for-Alfred#22]
I install the workflow step by step, but it not work for me when I use 'trello' commend.
I'm sure the 'bin/bash' have configured。

Environmental information：
masOS mojave 10.14
Trello have logged in

Please give me some advice,TKS.

**Comment by MikoMagni** [comment]
Did you generate the Trello Dev API key and Authorized the WorkFlow with your Trello account?

You need to be logged in Trello to generate the API key and to use the workflow.
