### ISSUE TITLE
Unable to create Trello Card

### ISSUE THREAD

**Issue by jeffpees** [MikoMagni/Trello-Workflow-for-Alfred#23]
Hi there, unable to create new cards after supplying valid token, api key, and board ID. The logs provided via Alfred. Using Alfred 3.8.1 Build 961 - reach out if you need any clarification.

Starting debug for 'Trello Worklfow for Alfred v.1.6.1'

[2019-04-04 14:20:34][input.keyword] Processing output of 'action.script' with arg 'this is a test'
[2019-04-04 14:20:35][action.script] Processing output of 'output.notification' with arg '
Warning: Invalid argument supplied for foreach() in /Users/jeffrep/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.CCFA8AA6-CC90-450A-9665-52139CC50589/trello.php on line 49
List not found'
[2019-04-04 14:20:35][action.script] Processing output of 'output.playsound' with arg '
Warning: Invalid argument supplied for foreach() in /Users/jeffrep/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.CCFA8AA6-CC90-450A-9665-52139CC50589/trello.php on line 49
List not found'

**Comment by MikoMagni** [comment]
Hi Jeff, 

Silly question (but I have to ask) do you have a list on your board?  

Have you tripled checked that your list id is correct?



> **Your Trello board id**
> Choose the Trello board that you wish to use with Trello Workflow and copy the board id
> You can get the board id by simply going to your board and add .json at the end of the URL.
> 
> **Example:** Go to the Trello development Roadmap Board https://trello.com/b/nC8QJJoZ/trello-development-roadmap. To view the board id add .json at the end of the URL https://trello.com/b/nC8QJJoZ/trello-development-roadmap.json. You should now see the full JSON
> 
>    ` {"id":"4d5ea62fd76aa1136000000c","name":"Trello Development Roadmap","desc":"","descData"`
> 
> The board id in the example is: **4d5ea62fd76aa1136000000c**
> 

Did you enter the key, token and boardid in the bash without any spaces?

key='**00000000000000000**'
token='**00000000000000000000000000000000000**' 
boardid='**0000000000000**'


Otherwise feel free to invite me to your test Trello board and happy to have a look at it.

**Comment by MikoMagni** [comment]
HI Jeff, 

I have managed to reproduce your error by adding an extra space in the board id.

> [2019-04-05 12:23:59][action.script] Processing output of 'output.playsound' with arg '
> Warning: Invalid argument supplied for foreach() in /Users/miko/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EFA39484-AB24-4A52-AEEA-2E2D1D0D2943/trello.php on line 49
> List not found'

Can you please have a look and let me know?
