### ISSUE TITLE
Getting board id doesn't work

### ISSUE THREAD

**Issue by lessthanzero** [MikoMagni/Trello-Workflow-for-Alfred#24]
Hi! I'm trying to get the id for the board, but keep getting the 404 error. The board is private, tho. Does this work only for public boards?

**Comment by MikoMagni** [comment]
Are you getting the 404 in Trello when you try to change the URL .json to get the correct board ID?

I only use the workflow in private boards, so that is not an issue.

**Comment by lessthanzero** [comment]
@MikoMagni well, yeah. But through the Trello support I've found a workaround: in the board menu (upper-right corner) there's an Export option. So you can find the board id in the exported JSON.
