### ISSUE TITLE
Alternate parameters

### ISSUE THREAD

**Issue by cfdynamics** [MikoMagni/Trello-Workflow-for-Alfred#9]
Often I need to put an item to a specific list but don't need to put a label or due date.  It would be nice to do card;description;list - but it always goes to the first list on the board.

**Comment by politicus** [comment]
+1 I tried the example you give "trello Do work!; seriously, do work; red; 09/01/2015; Inbox". It always goes to the first list on the board.

**Comment by escherize** [comment]
+1 for the ablility to add to a specific list

**Comment by sarumont** [comment]
This works for me, guys. Make sure you don't have spaces after the `;`. You can also skip arguments you don't want:

`trello Do work!;seriously;red,green;;Inbox` (adds to Inbox with red and green labels with no due date)
`trello Have fun;;;2015-07-11` (adds to the first list with no description, no labels, and a due date

**Comment by escherize** [comment]
Ahh, thanks @sarumont. Not sure how I missed that for so long! fucking great. :+1:

**Comment by zenimchan** [comment]
How do I change the  order of parameters?
